// The seeded directory for the fictional town of Ashford Vale. Every provider
// is a placeholder ("Pharmacy A", "Dr X's Practice"): nothing here refers to a
// real business, person or place. Imported by both the client and the server
// so simulated and live answers draw on exactly the same data.

import type { Category, District, OpenInterval, OpeningHours, Provider } from "./types";

export const TOWN = "Ashford Vale";

export const CATEGORIES: Category[] = [
  { id: "pharmacy", label: "Pharmacy", plural: "pharmacies" },
  { id: "gp", label: "GP practice", plural: "GP practices" },
  { id: "dentist", label: "Dentist", plural: "dentists" },
  { id: "optician", label: "Optician", plural: "opticians" },
  { id: "physio", label: "Physiotherapy", plural: "physiotherapists" },
  { id: "sexual-health", label: "Sexual health", plural: "sexual health clinics" },
  { id: "mental-health", label: "Mental health", plural: "mental health services" },
  { id: "urgent-care", label: "Urgent treatment", plural: "urgent treatment centres" },
  { id: "minor-injuries", label: "Minor injuries", plural: "minor injuries units" },
  { id: "podiatry", label: "Podiatry", plural: "podiatrists" },
];

export const CATEGORY_BY_ID = Object.fromEntries(CATEGORIES.map((c) => [c.id, c])) as Record<
  Category["id"],
  Category
>;

// Map: 100 × 70 viewBox. The river runs down the west side, the harbour along
// the south, the hill to the north-east.
export const DISTRICTS: District[] = [
  {
    id: "northgate",
    name: "Northgate",
    blurb: "The newer residential north, around the retail park and the ring road.",
    path: "M 24 2 L 58 2 L 60 24 L 32 26 L 26 18 Z",
    label: { x: 42, y: 13 },
  },
  {
    id: "hillcrest",
    name: "Hillcrest",
    blurb: "Quiet streets climbing the hill, with the community hospital at the top.",
    path: "M 58 2 L 98 2 L 98 30 L 64 32 L 60 24 Z",
    label: { x: 79, y: 15 },
  },
  {
    id: "riverside",
    name: "Riverside",
    blurb: "The long strip beside the river: flats, the station and late-opening shops.",
    path: "M 2 8 L 24 2 L 26 18 L 32 26 L 30 46 L 2 48 Z",
    label: { x: 15, y: 27 },
  },
  {
    id: "old-town",
    name: "Old Town",
    blurb: "The historic centre with the market square and most of the older practices.",
    path: "M 32 26 L 60 24 L 64 32 L 62 46 L 30 46 Z",
    label: { x: 47, y: 36 },
  },
  {
    id: "meadowbrook",
    name: "Meadowbrook",
    blurb: "Suburban estates and the leisure centre out towards the fields.",
    path: "M 64 32 L 98 30 L 98 68 L 62 68 L 62 46 Z",
    label: { x: 80, y: 50 },
  },
  {
    id: "harbour",
    name: "Harbour",
    blurb: "The old docks, now a mix of housing, the marina and the seafront.",
    path: "M 2 48 L 30 46 L 62 46 L 62 68 L 2 68 Z",
    label: { x: 32, y: 58 },
  },
];

export const DISTRICT_BY_ID = Object.fromEntries(DISTRICTS.map((d) => [d.id, d])) as Record<
  District["id"],
  District
>;

// ---- Opening-hours helpers -------------------------------------------------

const at = (open: string, close: string): OpenInterval => ({ open, close });
const closed: OpenInterval[] = [];

/** Mon–Fri one interval, optional Saturday and Sunday. */
function week(weekday: OpenInterval[], sat: OpenInterval[] = closed, sun: OpenInterval[] = closed): OpeningHours {
  return [sun, weekday, weekday, weekday, weekday, weekday, sat];
}

const OFFICE = week([at("09:00", "17:30")]);
const OFFICE_SAT = week([at("09:00", "17:30")], [at("09:00", "13:00")]);
const HIGH_STREET = week([at("08:30", "18:30")], [at("09:00", "17:00")]);
const HIGH_STREET_SUN = week([at("08:30", "18:30")], [at("09:00", "17:00")], [at("10:00", "16:00")]);
const LATE_EVERY_DAY = week([at("08:00", "23:00")], [at("08:00", "23:00")], [at("09:00", "23:00")]);
const GP_HOURS = week([at("08:00", "18:30")]);
const GP_EXTENDED = week([at("07:30", "20:00")], [at("09:00", "12:00")]);
const ALL_DAY = week([at("08:00", "20:00")], [at("08:00", "20:00")], [at("08:00", "20:00")]);
const ROUND_THE_CLOCK = week([at("00:00", "24:00")], [at("00:00", "24:00")], [at("00:00", "24:00")]);

/** Ofcom's reserved drama range for fictional UK numbers. */
const phone = (n: number) => `01632 960 ${String(n).padStart(3, "0")}`;

// ---- Providers --------------------------------------------------------------

export const PROVIDERS: Provider[] = [
  // Pharmacies. Only Pharmacy C is open late; only C and F open on Sunday.
  {
    id: "pharmacy-a",
    name: "Pharmacy A",
    category: "pharmacy",
    district: "northgate",
    tags: ["prescriptions", "repeat prescriptions", "flu jab", "vaccinations", "blood pressure check"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: HIGH_STREET,
    phone: phone(101),
    x: 38,
    y: 9,
    blurb: "Retail-park pharmacy with a consultation room for flu jabs and blood pressure checks.",
  },
  {
    id: "pharmacy-b",
    name: "Pharmacy B",
    category: "pharmacy",
    district: "old-town",
    tags: ["prescriptions", "repeat prescriptions", "travel vaccinations", "minor ailments"],
    nhs: true,
    walkIn: true,
    accessible: false,
    hours: OFFICE_SAT,
    phone: phone(102),
    x: 44,
    y: 34,
    blurb: "Independent pharmacy on the market square; two steps up to the door.",
  },
  {
    id: "pharmacy-c",
    name: "Pharmacy C",
    category: "pharmacy",
    district: "riverside",
    tags: [
      "late night",
      "prescriptions",
      "emergency prescriptions",
      "emergency contraception",
      "out of hours",
      "minor ailments",
    ],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: LATE_EVERY_DAY,
    phone: phone(103),
    x: 14,
    y: 20,
    blurb: "The town's late pharmacy, open until 23:00 every day, next to the station.",
  },
  {
    id: "pharmacy-d",
    name: "Pharmacy D",
    category: "pharmacy",
    district: "meadowbrook",
    tags: ["prescriptions", "repeat prescriptions", "delivery", "medicine review"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: HIGH_STREET,
    phone: phone(104),
    x: 82,
    y: 44,
    blurb: "Estate pharmacy attached to the Meadowbrook health centre; free delivery for repeats.",
  },
  {
    id: "pharmacy-e",
    name: "Pharmacy E",
    category: "pharmacy",
    district: "hillcrest",
    tags: ["prescriptions", "hospital discharge", "medicine review"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: OFFICE,
    phone: phone(105),
    x: 84,
    y: 12,
    blurb: "Small pharmacy at the community hospital entrance, weekdays only.",
  },
  {
    id: "pharmacy-f",
    name: "Pharmacy F",
    category: "pharmacy",
    district: "harbour",
    tags: ["prescriptions", "sunday", "emergency contraception", "travel vaccinations", "minor ailments"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: HIGH_STREET_SUN,
    phone: phone(106),
    x: 30,
    y: 62,
    blurb: "Seafront pharmacy open seven days, with a travel clinic on Saturdays.",
  },
  {
    id: "pharmacy-g",
    name: "Pharmacy G",
    category: "pharmacy",
    district: "old-town",
    tags: ["prescriptions", "compounding", "private prescriptions", "hearing aid batteries"],
    nhs: false,
    walkIn: true,
    accessible: true,
    hours: OFFICE,
    phone: phone(107),
    x: 55,
    y: 40,
    blurb: "Private dispensing pharmacy; does not take NHS prescriptions.",
  },

  // GP practices. Dr X's Practice is the only one taking new NHS patients.
  {
    id: "gp-x",
    name: "Dr X's Practice",
    category: "gp",
    district: "northgate",
    tags: ["new patients", "registering", "accepting patients", "online booking", "nurse clinic"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: GP_HOURS,
    phone: phone(201),
    x: 50,
    y: 16,
    blurb: "Large practice on the ring road, currently accepting new NHS patients.",
  },
  {
    id: "gp-y",
    name: "Dr Y's Practice",
    category: "gp",
    district: "old-town",
    tags: ["list closed", "same day", "walk-in clinic", "morning clinic", "nurse clinic"],
    nhs: true,
    walkIn: true,
    accessible: false,
    hours: GP_HOURS,
    phone: phone(202),
    x: 36,
    y: 40,
    blurb: "Market-square practice with a same-day walk-in clinic 08:00–10:00 for registered patients; list currently closed.",
  },
  {
    id: "gp-z",
    name: "Dr Z's Practice",
    category: "gp",
    district: "meadowbrook",
    tags: ["list closed", "extended hours", "evening appointments", "saturday", "baby clinic"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: GP_EXTENDED,
    phone: phone(203),
    x: 76,
    y: 54,
    blurb: "Health-centre practice with evening and Saturday morning appointments; list currently closed.",
  },
  {
    id: "gp-w",
    name: "Dr W's Practice",
    category: "gp",
    district: "riverside",
    tags: ["list closed", "phone triage", "interpreter"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: GP_HOURS,
    phone: phone(204),
    x: 18,
    y: 38,
    blurb: "Small riverside practice running phone-first triage; list currently closed.",
  },
  {
    id: "gp-private",
    name: "Private GP Clinic A",
    category: "gp",
    district: "hillcrest",
    tags: ["private", "same day", "travel medicine", "medicals", "no registration"],
    nhs: false,
    walkIn: false,
    accessible: true,
    hours: OFFICE_SAT,
    phone: phone(205),
    x: 70,
    y: 22,
    blurb: "Private clinic offering same-day paid appointments without registering.",
  },

  // Dentists. Only Dental Practice B takes NHS patients; D has emergency slots.
  {
    id: "dentist-a",
    name: "Dental Practice A",
    category: "dentist",
    district: "northgate",
    tags: ["private", "hygienist", "whitening", "invisalign"],
    nhs: false,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(301),
    x: 30,
    y: 18,
    blurb: "Private practice specialising in cosmetic and orthodontic work.",
  },
  {
    id: "dentist-b",
    name: "Dental Practice B",
    category: "dentist",
    district: "old-town",
    tags: ["nhs", "accepting nhs patients", "new patients", "children", "hygienist"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(302),
    x: 50,
    y: 30,
    blurb: "The only practice in town currently accepting new NHS patients, including children.",
  },
  {
    id: "dentist-c",
    name: "Dental Practice C",
    category: "dentist",
    district: "meadowbrook",
    tags: ["private", "nhs children only", "hygienist", "sedation"],
    nhs: false,
    walkIn: false,
    accessible: true,
    hours: OFFICE_SAT,
    phone: phone(303),
    x: 90,
    y: 60,
    blurb: "Mostly private; NHS places for existing child patients only.",
  },
  {
    id: "dentist-d",
    name: "Dental Practice D",
    category: "dentist",
    district: "harbour",
    tags: ["emergency dentist", "toothache", "same day", "private", "out of hours"],
    nhs: false,
    walkIn: true,
    accessible: true,
    hours: week([at("08:00", "20:00")], [at("09:00", "17:00")], [at("10:00", "14:00")]),
    phone: phone(304),
    x: 48,
    y: 58,
    blurb: "Private practice holding daily emergency slots for toothache and broken teeth, seven days.",
  },
  {
    id: "dentist-e",
    name: "Dental Practice E",
    category: "dentist",
    district: "hillcrest",
    tags: ["private", "implants", "hygienist"],
    nhs: false,
    walkIn: false,
    accessible: false,
    hours: OFFICE,
    phone: phone(305),
    x: 92,
    y: 20,
    blurb: "Private practice on the first floor of a converted house; no lift.",
  },

  // Urgent and minor injuries.
  {
    id: "urgent-care",
    name: "Urgent Treatment Centre",
    category: "urgent-care",
    district: "hillcrest",
    tags: ["urgent", "x-ray", "walk-in", "24 hours", "fractures", "burns", "cuts", "stitches", "out of hours gp"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: ROUND_THE_CLOCK,
    phone: phone(401),
    x: 78,
    y: 8,
    blurb: "At the community hospital, open 24 hours for injuries and illnesses that are urgent but not life-threatening. Not an A&E.",
  },
  {
    id: "minor-injuries",
    name: "Minor Injuries Unit",
    category: "minor-injuries",
    district: "harbour",
    tags: ["cuts", "stitches", "sprains", "x-ray", "walk-in", "burns", "bites", "splinters", "eye injuries"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: ALL_DAY,
    phone: phone(402),
    x: 14,
    y: 56,
    blurb: "Nurse-led walk-in unit for cuts, sprains and minor burns, with x-ray on site until 20:00.",
  },

  // Sexual health, mental health.
  {
    id: "sexual-health",
    name: "Sexual Health Clinic",
    category: "sexual-health",
    district: "riverside",
    tags: ["walk-in", "sti testing", "contraception", "emergency contraception", "prep", "confidential", "under 25s"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: [closed, [at("09:00", "17:00")], [at("09:00", "19:30")], [at("09:00", "17:00")], [at("09:00", "19:30")], [at("09:00", "16:00")], closed],
    phone: phone(501),
    x: 22,
    y: 30,
    blurb: "Free, confidential NHS clinic. Walk-in sessions Tuesday and Thursday evenings, appointments otherwise.",
  },
  {
    id: "mental-health-dropin",
    name: "Wellbeing Drop-in",
    category: "mental-health",
    district: "old-town",
    tags: ["drop-in", "walk-in", "anxiety", "low mood", "talking", "peer support", "crisis"],
    nhs: false,
    walkIn: true,
    accessible: true,
    hours: week([at("10:00", "20:00")], [at("10:00", "16:00")]),
    phone: phone(502),
    x: 40,
    y: 30,
    blurb: "Charity-run drop-in above the library: no referral, someone to talk to the same day.",
  },
  {
    id: "mental-health-talking",
    name: "Talking Therapies Service",
    category: "mental-health",
    district: "meadowbrook",
    tags: ["self-referral", "cbt", "counselling", "anxiety", "depression", "appointment"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(503),
    x: 70,
    y: 40,
    blurb: "NHS talking therapies; self-refer online or by phone, first appointment usually within three weeks.",
  },

  // Opticians.
  {
    id: "optician-a",
    name: "Optician A",
    category: "optician",
    district: "northgate",
    tags: ["eye test", "glasses", "contact lenses", "nhs eye test", "children"],
    nhs: true,
    walkIn: true,
    accessible: true,
    hours: HIGH_STREET,
    phone: phone(601),
    x: 44,
    y: 20,
    blurb: "Retail-park optician with same-day eye tests and NHS vouchers.",
  },
  {
    id: "optician-b",
    name: "Optician B",
    category: "optician",
    district: "old-town",
    tags: ["eye test", "glasses", "contact lenses", "urgent eye", "red eye", "minor eye conditions"],
    nhs: true,
    walkIn: false,
    accessible: false,
    hours: OFFICE_SAT,
    phone: phone(602),
    x: 58,
    y: 34,
    blurb: "Independent optician offering the NHS minor eye conditions service for sudden red or painful eyes.",
  },
  {
    id: "optician-c",
    name: "Optician C",
    category: "optician",
    district: "harbour",
    tags: ["eye test", "glasses", "home visits", "low vision"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(603),
    x: 56,
    y: 62,
    blurb: "Small practice doing home visits for people who cannot travel.",
  },

  // Physiotherapy and podiatry.
  {
    id: "physio-a",
    name: "Physiotherapy Clinic A",
    category: "physio",
    district: "meadowbrook",
    tags: ["sports injury", "back pain", "private", "self-referral", "sprains"],
    nhs: false,
    walkIn: false,
    accessible: true,
    hours: week([at("07:00", "20:00")], [at("08:00", "13:00")]),
    phone: phone(701),
    x: 88,
    y: 36,
    blurb: "Private clinic at the leisure centre with early and evening slots.",
  },
  {
    id: "physio-b",
    name: "Physiotherapy Clinic B",
    category: "physio",
    district: "hillcrest",
    tags: ["nhs", "referral", "post-operative", "falls", "back pain"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(702),
    x: 66,
    y: 12,
    blurb: "NHS outpatient physiotherapy at the community hospital; GP or self-referral.",
  },
  {
    id: "physio-c",
    name: "Physiotherapy Clinic C",
    category: "physio",
    district: "riverside",
    tags: ["private", "pilates", "women's health", "back pain"],
    nhs: false,
    walkIn: false,
    accessible: false,
    hours: OFFICE,
    phone: phone(703),
    x: 10,
    y: 42,
    blurb: "Private studio by the river, first floor, no lift.",
  },
  {
    id: "podiatry-a",
    name: "Podiatry Clinic A",
    category: "podiatry",
    district: "old-town",
    tags: ["private", "ingrown toenail", "verruca", "orthotics", "nail cutting"],
    nhs: false,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(801),
    x: 34,
    y: 44,
    blurb: "Private chiropody and podiatry off the market square.",
  },
  {
    id: "podiatry-b",
    name: "Podiatry Clinic B",
    category: "podiatry",
    district: "harbour",
    tags: ["nhs", "diabetic foot", "referral", "wound care"],
    nhs: true,
    walkIn: false,
    accessible: true,
    hours: OFFICE,
    phone: phone(802),
    x: 40,
    y: 52,
    blurb: "NHS podiatry for high-risk feet, mainly diabetes; GP referral needed.",
  },
];

export const PROVIDER_BY_ID = Object.fromEntries(PROVIDERS.map((p) => [p.id, p])) as Record<string, Provider>;
